INSERT INTO tag_content (the_tag_content) VALUES('#SPORT');
INSERT INTO tag_content (the_tag_content) VALUES('#MUSIC');
INSERT INTO tag_content (the_tag_content) VALUES('#ART');
INSERT INTO tag_content (the_tag_content) VALUES('#CELEBRITIES');
INSERT INTO tag_content (the_tag_content) VALUES('#VEHICLES');
INSERT INTO tag_content (the_tag_content) VALUES('#NEWS');
INSERT INTO tag_content (the_tag_content) VALUES('#POLITICS');
INSERT INTO tag_content (the_tag_content) VALUES('#HISTORY & GEOGRAPHY');
INSERT INTO tag_content (the_tag_content) VALUES('#MEMES');
INSERT INTO tag_content (the_tag_content) VALUES('#FOOD & COOKING');
INSERT INTO tag_content (the_tag_content) VALUES('#GAMING');
INSERT INTO tag_content (the_tag_content) VALUES('#CODING');
INSERT INTO tag_content (the_tag_content) VALUES('#MOVIES & SERIES');
INSERT INTO tag_content (the_tag_content) VALUES('#NATURE');
INSERT INTO tag_content (the_tag_content) VALUES('#TV-SHOWS');
INSERT INTO tag_content (the_tag_content) VALUES('#CRYPTO');
INSERT INTO tag_content (the_tag_content) VALUES('#STOCKS');
-- DO THE UPPER FIRST !!!
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (5,1);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (12,33);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (14,51);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (11,59);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (2,90);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (1,113);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (3,117);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (4,149);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (5,157);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (6,114);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (7,173);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (8,160);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (9,156);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (10,2);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (13,226);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (15,242);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (16,224);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (17,191);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (17,256);
INSERT INTO tags (tag_to_tag_content,tag_to_post) VALUES (1,40);